#!/bin/sh
### BEGIN INIT INFO
# Provides:          docker_env
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Set Docker credentials as environment variables
# Description:       Exports DOCKER_USERNAME and DOCKER_TOKEN for system-wide use
### END INIT INFO

# Customize your Docker credentials here
DOCKER_USERNAME="huzaifapatel"
DOCKER_TOKEN="theelitehuzi007"

# File to export environment variables
ENV_FILE="/etc/profile.d/docker_env.sh"

case "$1" in
  start)
    echo "Exporting Docker environment variables..."
    echo "export DOCKER_USERNAME=\"$DOCKER_USERNAME\"" > "$ENV_FILE"
    echo "export DOCKER_TOKEN=\"$DOCKER_TOKEN\"" >> "$ENV_FILE"
    chmod +x "$ENV_FILE"
    ;;
  stop)
    echo "Removing Docker environment variables..."
    rm -f "$ENV_FILE"
    ;;
  restart)
    "$0" stop
    "$0" start
    ;;
  *)
    echo "Usage: /etc/init.d/docker_env {start|stop|restart}"
    exit 1
    ;;
esac

exit 0
